import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
//useSWR allows the use of SWR inside function components
import useSWR from 'swr';

const inter = Inter({ subsets: ['latin'] });

//Write a fetcher function to wrap the native fetch function and return the result of a call to url in json format
const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  //Set up SWR to run the fetcher function when calling "/api/staticdata"
  //There are 3 possible states: (1) loading when data is null (2) ready when the data is returned (3) error when there was an error fetching the data
  let { data, error } = useSWR('/api/staticdata', fetcher);

  //Handle the error state
  if (error) return <div>Failed to load</div>;
  //Handle the loading state
  if (!data) return <div>Loading...</div>;
  //Handle the ready state and display the result contained in the data object mapped to the structure of the json file
  data = JSON.parse(data);
  console.log(
    data.record.map((r) => {
      return r.id;
    })
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <div>
      <h1>My Framework from file</h1>
      <ul>
        <li>Name: {data.title}</li>
        <li>Language: {data.language}</li>
      </ul>
    </div> */}

      <header className='header'>
        <img src='/logo.png' alt='Backstage Logo' className='logo' />

        <p className='contact'>
          <a className='link2' href='mailto:info@backstagetalks.com'>
            info@backstagetalks.com
          </a>
        </p>
      </header>
      <main className={styles.main}>
        <div id='fullpage'>
          {data.record.map(r => {
            return (
              <section
                key={`${r.id}`}
                className='section'
                data-anchor={`issue${r.id}`}
                style={{
                  backgroundColor: `var(${r.backgroundColor})`
                }}
              
              >
                <img
                  src={r.img}
                  alt={`Backstage talks Issue ${r.id}`}
                  className='cover'
                />
                <h2>
                  Issue #{r.id} {!r.available && <> is sold out</>}
                </h2>

                {r.available && (
                  <div className='avail'>
                    <h3>
                      <a href={`${r.linkToBuy}`}
                       style={{
                        color: `var(${r.linkColor})`
                      }}>
                        BUY HERE
                      </a>
                    </h3>
                  </div>
                )}
                <p>
                  {r.available && <>or in </>}
                  {!r.available && (
                    <>If you are lucky, you may get the last pieces in </>
                  )}
                  <a href='http://backstagetalks.com/stocklist.php'
                  style={{
                    color: `var(${r.linkColor})`}}>
                     selected stores
                  </a>
                  .
                </p>
              </section>
            );
          })}


    

          <footer className='footer'>
            <p className='description'>
              Backstage Talks is a&nbsp;magazine of&nbsp;casual, but
              in&nbsp;depth dialogues on&nbsp;design and business. Our decisions
              shape and influence this complex world—to have a&nbsp;chance
              to&nbsp;make the right ones, we need to talk.
            </p>

            <span className='copyright'>
              <h4>
                &copy; 2023{' '}
                <a href='http://milk.sk/' target='_blank'>
                  Published by studio Milk
                </a>
                . <br />
                Coded by <a href=''>Chanda Abdul</a>
              </h4>
            </span>

            <h5>
              <a href='/privacy-policy.php'>Privacy Policy</a>
            </h5>
            <ul className='menu'>
              <li>
                <a className='menulink issue6' href='#issue6'>
                  Issue #6
                </a>
              </li>
              <li>
                <a className='menulink issue5' href='#issue5'>
                  Issue #5
                </a>
              </li>
              <li>
                <a className='menulink issue4' href='#issue4'>
                  Issue #4
                </a>
              </li>
              <li>
                <a className='menulink issue3' href='#issue3'>
                  Issue #3
                </a>
              </li>
              <li>
                <a className='menulink issue2' href='#issue2'>
                  Issue #2
                </a>
              </li>
              <li>
                <a className='menulink issue1' href='#issue1'>
                  Issue #1
                </a>
              </li>
            </ul>
            <p className=''>
              <a className='link2' href='mailto:info@backstagetalks.com'>
                info@backstagetalks.com
              </a>
            </p>
          </footer>
        </div>
      </main>
    </>
  );
}
